module.exports = () => {
 return [
      {
        LatestUpdate: '2017-04-29T12:11:14',
        DataAge: 57,
        Metros: [
          {
            GroupOfLine: 'tunnelbanans gröna linje',
            DisplayTime: '2 min',
            TransportMode: 'METRO',
            LineNumber: '17',
            Destination: 'Åkeshov',
            JourneyDirection: 1,
            StopAreaName: 'Odenplan',
            StopAreaNumber: 1131,
            StopPointNumber: 1131,
            StopPointDesignation: '1',
            TimeTabledDateTime: '2017-04-29T12:14:30',
            ExpectedDateTime: '2017-04-29T12:14:30',
            JourneyNumber: 10944,
            Deviations: null
          },
          {
            GroupOfLine: 'tunnelbanans gröna linje',
            DisplayTime: '3 min',
            TransportMode: 'METRO',
            LineNumber: '18',
            Destination: 'Farsta strand',
            JourneyDirection: 2,
            StopAreaName: 'Odenplan',
            StopAreaNumber: 1131,
            StopPointNumber: 1132,
            StopPointDesignation: '2',
            TimeTabledDateTime: '2017-04-29T12:15:30',
            ExpectedDateTime: '2017-04-29T12:15:30',
            JourneyNumber: 10134,
            Deviations: null
          },
          {
            GroupOfLine: 'tunnelbanans gröna linje',
            DisplayTime: '4 min',
            TransportMode: 'METRO',
            LineNumber: '18',
            Destination: 'Hässelby strand',
            JourneyDirection: 1,
            StopAreaName: 'Odenplan',
            StopAreaNumber: 1131,
            StopPointNumber: 1131,
            StopPointDesignation: '1',
            TimeTabledDateTime: '2017-04-29T12:17:00',
            ExpectedDateTime: '2017-04-29T12:17:00',
            JourneyNumber: 10344,
            Deviations: null
          },
          {
            GroupOfLine: 'tunnelbanans gröna linje',
            DisplayTime: '6 min',
            TransportMode: 'METRO',
            LineNumber: '19',
            Destination: 'Hagsätra',
            JourneyDirection: 2,
            StopAreaName: 'Odenplan',
            StopAreaNumber: 1131,
            StopPointNumber: 1132,
            StopPointDesignation: '2',
            TimeTabledDateTime: '2017-04-29T12:18:30',
            ExpectedDateTime: '2017-04-29T12:18:30',
            JourneyNumber: 10697,
            Deviations: null
          },
          {
            GroupOfLine: 'tunnelbanans gröna linje',
            DisplayTime: '8 min',
            TransportMode: 'METRO',
            LineNumber: '19',
            Destination: 'Alvik',
            JourneyDirection: 1,
            StopAreaName: 'Odenplan',
            StopAreaNumber: 1131,
            StopPointNumber: 1131,
            StopPointDesignation: '1',
            TimeTabledDateTime: '2017-04-29T12:20:30',
            ExpectedDateTime: '2017-04-29T12:20:30',
            JourneyNumber: 10580,
            Deviations: null
          },
          {
            GroupOfLine: 'tunnelbanans gröna linje',
            DisplayTime: '9 min',
            TransportMode: 'METRO',
            LineNumber: '17',
            Destination: 'Skarpnäck',
            JourneyDirection: 2,
            StopAreaName: 'Odenplan',
            StopAreaNumber: 1131,
            StopPointNumber: 1132,
            StopPointDesignation: '2',
            TimeTabledDateTime: '2017-04-29T12:21:30',
            ExpectedDateTime: '2017-04-29T12:21:30',
            JourneyNumber: 11084,
            Deviations: null
          },
          {
            GroupOfLine: 'tunnelbanans gröna linje',
            DisplayTime: '12 min',
            TransportMode: 'METRO',
            LineNumber: '17',
            Destination: 'Åkeshov',
            JourneyDirection: 1,
            StopAreaName: 'Odenplan',
            StopAreaNumber: 1131,
            StopPointNumber: 1131,
            StopPointDesignation: '1',
            TimeTabledDateTime: '2017-04-29T12:24:30',
            ExpectedDateTime: '2017-04-29T12:24:30',
            JourneyNumber: 10945,
            Deviations: null
          },
          {
            GroupOfLine: 'tunnelbanans gröna linje',
            DisplayTime: '12:25',
            TransportMode: 'METRO',
            LineNumber: '18',
            Destination: 'Farsta strand',
            JourneyDirection: 2,
            StopAreaName: 'Odenplan',
            StopAreaNumber: 1131,
            StopPointNumber: 1132,
            StopPointDesignation: '2',
            TimeTabledDateTime: '2017-04-29T12:25:30',
            ExpectedDateTime: '2017-04-29T12:25:30',
            JourneyNumber: 10135,
            Deviations: null
          }
        ],
        Buses: [
          {
            GroupOfLine: 'blåbuss',
            TransportMode: 'BUS',
            LineNumber: '4',
            Destination: 'Radiohuset',
            JourneyDirection: 2,
            StopAreaName: 'Odenplan',
            StopAreaNumber: 10151,
            StopPointNumber: 10341,
            StopPointDesignation: 'C',
            TimeTabledDateTime: '2017-04-29T12:11:00',
            ExpectedDateTime: '2017-04-29T12:11:22',
            DisplayTime: 'Nu',
            JourneyNumber: 3170,
            Deviations: null
          },
          {
            GroupOfLine: 'blåbuss',
            TransportMode: 'BUS',
            LineNumber: '4',
            Destination: 'Radiohuset',
            JourneyDirection: 2,
            StopAreaName: 'Odenplan',
            StopAreaNumber: 10151,
            StopPointNumber: 10341,
            StopPointDesignation: 'C',
            TimeTabledDateTime: '2017-04-29T12:05:00',
            ExpectedDateTime: '2017-04-29T12:11:33',
            DisplayTime: 'Nu',
            JourneyNumber: 3169,
            Deviations: null
          },
          {
            GroupOfLine: null,
            TransportMode: 'BUS',
            LineNumber: '50',
            Destination: 'Stora Lappkärrsberget',
            JourneyDirection: 1,
            StopAreaName: 'Odenplan',
            StopAreaNumber: 10151,
            StopPointNumber: 10343,
            StopPointDesignation: 'B',
            TimeTabledDateTime: '2017-04-29T12:12:00',
            ExpectedDateTime: '2017-04-29T12:12:00',
            DisplayTime: 'Nu',
            JourneyNumber: 2705,
            Deviations: null
          },
          {
            GroupOfLine: 'blåbuss',
            TransportMode: 'BUS',
            LineNumber: '4',
            Destination: 'Gullmarsplan',
            JourneyDirection: 1,
            StopAreaName: 'Odenplan',
            StopAreaNumber: 10151,
            StopPointNumber: 10232,
            StopPointDesignation: 'F',
            TimeTabledDateTime: '2017-04-29T12:12:00',
            ExpectedDateTime: '2017-04-29T12:12:00',
            DisplayTime: '12:12',
            JourneyNumber: 3674,
            Deviations: null
          },
          {
            GroupOfLine: null,
            TransportMode: 'BUS',
            LineNumber: '69',
            Destination: 'Karolinska institutet',
            JourneyDirection: 2,
            StopAreaName: 'Odenplan',
            StopAreaNumber: 10151,
            StopPointNumber: 10342,
            StopPointDesignation: 'J',
            TimeTabledDateTime: '2017-04-29T12:14:00',
            ExpectedDateTime: '2017-04-29T12:14:00',
            DisplayTime: '12:14',
            JourneyNumber: 10013,
            Deviations: [
              {
                Text: 'Förändringar i busstrafiken 1 maj på grund av demonstrationer i innerstan. Se sl.se',
                Consequence: 'INFORMATION',
                ImportanceLevel: 2
              }
            ]
          },
          {
            GroupOfLine: null,
            TransportMode: 'BUS',
            LineNumber: '515',
            Destination: 'Sundbybergs station',
            JourneyDirection: 1,
            StopAreaName: 'Odenplan',
            StopAreaNumber: 10151,
            StopPointNumber: 10345,
            StopPointDesignation: 'A',
            TimeTabledDateTime: '2017-04-29T12:14:00',
            ExpectedDateTime: '2017-04-29T12:14:00',
            DisplayTime: '1 min',
            JourneyNumber: 20459,
            Deviations: null
          },
          {
            GroupOfLine: 'blåbuss',
            TransportMode: 'BUS',
            LineNumber: '2',
            Destination: 'Norrtull',
            JourneyDirection: 2,
            StopAreaName: 'Odenplan',
            StopAreaNumber: 10151,
            StopPointNumber: 10186,
            StopPointDesignation: 'G',
            TimeTabledDateTime: '2017-04-29T12:10:00',
            ExpectedDateTime: '2017-04-29T12:15:26',
            DisplayTime: '3 min',
            JourneyNumber: 6035,
            Deviations: [
              {
                Text: 'Förändringar i busstrafiken 1 maj på grund av demonstrationer i innerstan. Se sl.se',
                Consequence: 'INFORMATION',
                ImportanceLevel: 2
              }
            ]
          },
          {
            GroupOfLine: 'blåbuss',
            TransportMode: 'BUS',
            LineNumber: '4',
            Destination: 'Radiohuset',
            JourneyDirection: 2,
            StopAreaName: 'Odenplan',
            StopAreaNumber: 10151,
            StopPointNumber: 10341,
            StopPointDesignation: 'C',
            TimeTabledDateTime: '2017-04-29T12:17:00',
            ExpectedDateTime: '2017-04-29T12:17:00',
            DisplayTime: '4 min',
            JourneyNumber: 3171,
            Deviations: null
          }
        ],
        Trains: [],
        Trams: [],
        Ships: [],
        StopPointDeviations: [
          {
            StopInfo: {
              StopAreaNumber: 10151,
              StopAreaName: 'Odenplan',
              TransportMode: 'BUS',
              GroupOfLine: ''
            },
            Deviation: {
              Text: 'Förändringar i busstrafiken 1 maj på grund av demonstrationer i innerstan. Se sl.se',
              Consequence: null,
              ImportanceLevel: 2
            }
          },
          {
            StopInfo: {
              StopAreaNumber: 10151,
              StopAreaName: 'Odenplan',
              TransportMode: 'BUS',
              GroupOfLine: ''
            },
            Deviation: {
              Text: 'Förändringar i busstrafiken 29 april på grund av en klimatmanifestation i innerstan. Se sl.se',
              Consequence: null,
              ImportanceLevel: 2
            }
          },
          {
            StopInfo: {
              StopAreaNumber: 1131,
              StopAreaName: 'Odenplan',
              TransportMode: 'METRO',
              GroupOfLine: 'tunnelbanans gröna linje'
            },
            Deviation: {
              Text: 'Tvärbanan: Bussar mellan Thorildsplan och Sickla udde ersätter spårvagnstrafiken Alvik-Sickla udde  t.o.m.1 oktober. Mellan Alvik och Thorildsplan hänvisas till tunnelbanan. Läs mer på sl.se.',
              Consequence: null,
              ImportanceLevel: 2
            }
          },
          {
            StopInfo: {
              StopAreaNumber: 1131,
              StopAreaName: 'Odenplan',
              TransportMode: 'METRO',
              GroupOfLine: 'tunnelbanans gröna linje'
            },
            Deviation: {
              Text: 'Innerstadsbussarna: Förändringar i busstrafiken måndag 1 maj ca kl. 10:30-17:15 på grund av demostrationer. Läs mer på sl.se',
              Consequence: null,
              ImportanceLevel: 7
            }
          }
        ],
        StopAreaName: 'Odenplan'
      },
      {
        LatestUpdate: '2017-04-29T12:11:46',
        DataAge: 25,
        Metros: [],
        Buses: [
          {
            GroupOfLine: null,
            TransportMode: 'BUS',
            LineNumber: '72',
            Destination: 'Frihamnen',
            JourneyDirection: 1,
            StopAreaName: 'Karlbergs station',
            StopAreaNumber: 10135,
            StopPointNumber: 10175,
            StopPointDesignation: null,
            TimeTabledDateTime: '2017-04-29T12:15:00',
            ExpectedDateTime: '2017-04-29T12:15:00',
            DisplayTime: '2 min',
            JourneyNumber: 3316,
            Deviations: null
          },
          {
            GroupOfLine: null,
            TransportMode: 'BUS',
            LineNumber: '72',
            Destination: 'Frihamnen',
            JourneyDirection: 1,
            StopAreaName: 'Karlbergs station',
            StopAreaNumber: 10135,
            StopPointNumber: 10175,
            StopPointDesignation: null,
            TimeTabledDateTime: '2017-04-29T12:35:00',
            ExpectedDateTime: '2017-04-29T12:35:00',
            DisplayTime: '22 min',
            JourneyNumber: 3317,
            Deviations: null
          },
          {
            GroupOfLine: null,
            TransportMode: 'BUS',
            LineNumber: '507',
            Destination: 'Västra skogen',
            JourneyDirection: 1,
            StopAreaName: 'Karlbergs station',
            StopAreaNumber: 10135,
            StopPointNumber: 10173,
            StopPointDesignation: null,
            TimeTabledDateTime: '2017-04-29T12:38:00',
            ExpectedDateTime: '2017-04-29T12:38:00',
            DisplayTime: '12:38',
            JourneyNumber: 20494,
            Deviations: null
          }
        ],
        Trains: [
          {
            SecondaryDestinationName: null,
            GroupOfLine: null,
            TransportMode: 'TRAIN',
            LineNumber: '38',
            Destination: 'Uppsala C',
            JourneyDirection: 2,
            StopAreaName: 'Karlberg',
            StopAreaNumber: 5021,
            StopPointNumber: 5022,
            StopPointDesignation: '3',
            TimeTabledDateTime: '2017-04-29T12:12:00',
            ExpectedDateTime: '2017-04-29T12:12:00',
            DisplayTime: 'Nu',
            JourneyNumber: 2230,
            Deviations: [
              {
                Text: 'Resa förbi Arlanda C kräver både UL- och SL- biljett.',
                Consequence: 'INFORMATION',
                ImportanceLevel: 5
              }
            ]
          },
          {
            SecondaryDestinationName: null,
            GroupOfLine: null,
            TransportMode: 'TRAIN',
            LineNumber: '35',
            Destination: 'Västerhaninge',
            JourneyDirection: 1,
            StopAreaName: 'Karlberg',
            StopAreaNumber: 5021,
            StopPointNumber: 5021,
            StopPointDesignation: '2',
            TimeTabledDateTime: '2017-04-29T12:13:00',
            ExpectedDateTime: '2017-04-29T12:13:00',
            DisplayTime: 'Nu',
            JourneyNumber: 2531,
            Deviations: null
          },
          {
            SecondaryDestinationName: null,
            GroupOfLine: null,
            TransportMode: 'TRAIN',
            LineNumber: '35',
            Destination: 'Kungsängen',
            JourneyDirection: 2,
            StopAreaName: 'Karlberg',
            StopAreaNumber: 5021,
            StopPointNumber: 5022,
            StopPointDesignation: '3',
            TimeTabledDateTime: '2017-04-29T12:16:00',
            ExpectedDateTime: '2017-04-29T12:16:00',
            DisplayTime: '3 min',
            JourneyNumber: 2530,
            Deviations: null
          },
          {
            SecondaryDestinationName: null,
            GroupOfLine: null,
            TransportMode: 'TRAIN',
            LineNumber: '38',
            Destination: 'Älvsjö',
            JourneyDirection: 1,
            StopAreaName: 'Karlberg',
            StopAreaNumber: 5021,
            StopPointNumber: 5021,
            StopPointDesignation: '2',
            TimeTabledDateTime: '2017-04-29T12:17:00',
            ExpectedDateTime: '2017-04-29T12:17:00',
            DisplayTime: '4 min',
            JourneyNumber: 2231,
            Deviations: null
          },
          {
            SecondaryDestinationName: null,
            GroupOfLine: null,
            TransportMode: 'TRAIN',
            LineNumber: '36',
            Destination: 'Märsta',
            JourneyDirection: 2,
            StopAreaName: 'Karlberg',
            StopAreaNumber: 5021,
            StopPointNumber: 5022,
            StopPointDesignation: '3',
            TimeTabledDateTime: '2017-04-29T12:19:00',
            ExpectedDateTime: '2017-04-29T12:19:00',
            DisplayTime: '6 min',
            JourneyNumber: 2730,
            Deviations: null
          },
          {
            SecondaryDestinationName: null,
            GroupOfLine: null,
            TransportMode: 'TRAIN',
            LineNumber: '36',
            Destination: 'Södertälje centrum',
            JourneyDirection: 1,
            StopAreaName: 'Karlberg',
            StopAreaNumber: 5021,
            StopPointNumber: 5021,
            StopPointDesignation: '2',
            TimeTabledDateTime: '2017-04-29T12:25:00',
            ExpectedDateTime: '2017-04-29T12:25:00',
            DisplayTime: '12 min',
            JourneyNumber: 2631,
            Deviations: null
          },
          {
            SecondaryDestinationName: null,
            GroupOfLine: null,
            TransportMode: 'TRAIN',
            LineNumber: '35',
            Destination: 'Nynäshamn',
            JourneyDirection: 1,
            StopAreaName: 'Karlberg',
            StopAreaNumber: 5021,
            StopPointNumber: 5021,
            StopPointDesignation: '2',
            TimeTabledDateTime: '2017-04-29T12:28:00',
            ExpectedDateTime: '2017-04-29T12:28:00',
            DisplayTime: '15 min',
            JourneyNumber: 2831,
            Deviations: null
          },
          {
            SecondaryDestinationName: null,
            GroupOfLine: null,
            TransportMode: 'TRAIN',
            LineNumber: '35',
            Destination: 'Bålsta',
            JourneyDirection: 2,
            StopAreaName: 'Karlberg',
            StopAreaNumber: 5021,
            StopPointNumber: 5022,
            StopPointDesignation: '3',
            TimeTabledDateTime: '2017-04-29T12:31:00',
            ExpectedDateTime: '2017-04-29T12:31:00',
            DisplayTime: '18 min',
            JourneyNumber: 2830,
            Deviations: null
          }
        ],
        Trams: [],
        Ships: [],
        StopPointDeviations: [
          {
            StopInfo: {
              StopAreaNumber: 5021,
              StopAreaName: 'Karlberg',
              TransportMode: 'TRAIN',
              GroupOfLine: ''
            },
            Deviation: {
              Text: 'Sträckan Sundbyberg-Jakobsberg och omvänt ersätts med buss och tunnelbana söndagar till kl 08:50 pga banarbete. Se anslag på stationen samt sl.se.',
              Consequence: null,
              ImportanceLevel: 5
            }
          }
        ],
        StopAreaName: 'Karlbergs station'
      },
      {
        LatestUpdate: '2017-04-29T12:11:14',
        DataAge: 57,
        Metros: [],
        Buses: [
          {
            GroupOfLine: null,
            TransportMode: 'BUS',
            LineNumber: '61',
            Destination: 'Ruddammen',
            JourneyDirection: 2,
            StopAreaName: 'Valhallavägen',
            StopAreaNumber: 10193,
            StopPointNumber: 10193,
            StopPointDesignation: null,
            TimeTabledDateTime: '2017-04-29T12:13:24',
            ExpectedDateTime: '2017-04-29T12:13:24',
            DisplayTime: '1 min',
            JourneyNumber: 3527,
            Deviations: null
          },
          {
            GroupOfLine: null,
            TransportMode: 'BUS',
            LineNumber: '61',
            Destination: 'Hornsberg',
            JourneyDirection: 1,
            StopAreaName: 'Odengatan',
            StopAreaNumber: 10192,
            StopPointNumber: 10192,
            StopPointDesignation: null,
            TimeTabledDateTime: '2017-04-29T12:13:59',
            ExpectedDateTime: '2017-04-29T12:13:59',
            DisplayTime: '1 min',
            JourneyNumber: 3874,
            Deviations: null
          },
          {
            GroupOfLine: 'blåbuss',
            TransportMode: 'BUS',
            LineNumber: '4',
            Destination: 'Radiohuset',
            JourneyDirection: 2,
            StopAreaName: 'Valhallavägen',
            StopAreaNumber: 10193,
            StopPointNumber: 10193,
            StopPointDesignation: null,
            TimeTabledDateTime: '2017-04-29T12:15:09',
            ExpectedDateTime: '2017-04-29T12:15:31',
            DisplayTime: '3 min',
            JourneyNumber: 3170,
            Deviations: null
          },
          {
            GroupOfLine: 'blåbuss',
            TransportMode: 'BUS',
            LineNumber: '4',
            Destination: 'Radiohuset',
            JourneyDirection: 2,
            StopAreaName: 'Valhallavägen',
            StopAreaNumber: 10193,
            StopPointNumber: 10193,
            StopPointDesignation: null,
            TimeTabledDateTime: '2017-04-29T12:09:09',
            ExpectedDateTime: '2017-04-29T12:15:42',
            DisplayTime: '3 min',
            JourneyNumber: 3169,
            Deviations: null
          },
          {
            GroupOfLine: null,
            TransportMode: 'BUS',
            LineNumber: '67',
            Destination: 'Skansen',
            JourneyDirection: 1,
            StopAreaName: 'Valhallavägen',
            StopAreaNumber: 10193,
            StopPointNumber: 10193,
            StopPointDesignation: null,
            TimeTabledDateTime: '2017-04-29T12:15:55',
            ExpectedDateTime: '2017-04-29T12:15:55',
            DisplayTime: '3 min',
            JourneyNumber: 3093,
            Deviations: null
          },
          {
            GroupOfLine: 'blåbuss',
            TransportMode: 'BUS',
            LineNumber: '4',
            Destination: 'Gullmarsplan',
            JourneyDirection: 1,
            StopAreaName: 'Odengatan',
            StopAreaNumber: 10192,
            StopPointNumber: 10192,
            StopPointDesignation: null,
            TimeTabledDateTime: '2017-04-29T12:12:44',
            ExpectedDateTime: '2017-04-29T12:16:25',
            DisplayTime: '4 min',
            JourneyNumber: 3675,
            Deviations: null
          },
          {
            GroupOfLine: null,
            TransportMode: 'BUS',
            LineNumber: '72',
            Destination: 'Karlbergs station',
            JourneyDirection: 2,
            StopAreaName: 'Odengatan',
            StopAreaNumber: 10192,
            StopPointNumber: 10192,
            StopPointDesignation: null,
            TimeTabledDateTime: '2017-04-29T12:16:57',
            ExpectedDateTime: '2017-04-29T12:17:25',
            DisplayTime: '5 min',
            JourneyNumber: 4048,
            Deviations: null
          },
          {
            GroupOfLine: 'blåbuss',
            TransportMode: 'BUS',
            LineNumber: '4',
            Destination: 'Gullmarsplan',
            JourneyDirection: 1,
            StopAreaName: 'Odengatan',
            StopAreaNumber: 10192,
            StopPointNumber: 10192,
            StopPointDesignation: null,
            TimeTabledDateTime: '2017-04-29T12:19:44',
            ExpectedDateTime: '2017-04-29T12:19:44',
            DisplayTime: '7 min',
            JourneyNumber: 3676,
            Deviations: null
          }
        ],
        Trains: [],
        Trams: [],
        Ships: [],
        StopPointDeviations: [],
        StopAreaName: 'Valhallavägen'
      },
      {
        LatestUpdate: '2017-04-29T12:11:14',
        DataAge: 56,
        Metros: [],
        Buses: [
          {
            GroupOfLine: 'blåbuss',
            TransportMode: 'BUS',
            LineNumber: '179',
            Destination: 'Sollentuna station',
            JourneyDirection: 1,
            StopAreaName: 'Spånga station',
            StopAreaNumber: 12138,
            StopPointNumber: 50079,
            StopPointDesignation: 'B',
            TimeTabledDateTime: '2017-04-29T12:13:00',
            ExpectedDateTime: '2017-04-29T12:15:13',
            DisplayTime: '3 min',
            JourneyNumber: 20437,
            Deviations: null
          },
          {
            GroupOfLine: null,
            TransportMode: 'BUS',
            LineNumber: '514',
            Destination: 'Häggviks handelsplats',
            JourneyDirection: 1,
            StopAreaName: 'Spånga station',
            StopAreaNumber: 12138,
            StopPointNumber: 50079,
            StopPointDesignation: 'B',
            TimeTabledDateTime: '2017-04-29T12:16:00',
            ExpectedDateTime: '2017-04-29T12:16:00',
            DisplayTime: '3 min',
            JourneyNumber: 20465,
            Deviations: null
          },
          {
            GroupOfLine: null,
            TransportMode: 'BUS',
            LineNumber: '517',
            Destination: 'Kista centrum',
            JourneyDirection: 1,
            StopAreaName: 'Spånga station',
            StopAreaNumber: 12138,
            StopPointNumber: 12283,
            StopPointDesignation: 'E',
            TimeTabledDateTime: '2017-04-29T12:16:00',
            ExpectedDateTime: '2017-04-29T12:16:00',
            DisplayTime: '3 min',
            JourneyNumber: 41419,
            Deviations: null
          },
          {
            GroupOfLine: null,
            TransportMode: 'BUS',
            LineNumber: '112',
            Destination: 'Alvik',
            JourneyDirection: 1,
            StopAreaName: 'Spånga station',
            StopAreaNumber: 12138,
            StopPointNumber: 12324,
            StopPointDesignation: 'G',
            TimeTabledDateTime: '2017-04-29T12:16:00',
            ExpectedDateTime: '2017-04-29T12:16:00',
            DisplayTime: '3 min',
            JourneyNumber: 41409,
            Deviations: null
          },
          {
            GroupOfLine: null,
            TransportMode: 'BUS',
            LineNumber: '117',
            Destination: 'Brommaplan',
            JourneyDirection: 1,
            StopAreaName: 'Spånga station',
            StopAreaNumber: 12138,
            StopPointNumber: 12324,
            StopPointDesignation: 'G',
            TimeTabledDateTime: '2017-04-29T12:16:00',
            ExpectedDateTime: '2017-04-29T12:16:00',
            DisplayTime: '3 min',
            JourneyNumber: 41416,
            Deviations: null
          },
          {
            GroupOfLine: null,
            TransportMode: 'BUS',
            LineNumber: '119',
            Destination: 'Backlura',
            JourneyDirection: 2,
            StopAreaName: 'Spånga station',
            StopAreaNumber: 12138,
            StopPointNumber: 12138,
            StopPointDesignation: 'C',
            TimeTabledDateTime: '2017-04-29T12:16:00',
            ExpectedDateTime: '2017-04-29T12:16:00',
            DisplayTime: '12:16',
            JourneyNumber: 41404,
            Deviations: null
          },
          {
            GroupOfLine: null,
            TransportMode: 'BUS',
            LineNumber: '512',
            Destination: 'Solna centrum',
            JourneyDirection: 1,
            StopAreaName: 'Spånga station',
            StopAreaNumber: 12138,
            StopPointNumber: 50080,
            StopPointDesignation: 'A',
            TimeTabledDateTime: '2017-04-29T12:16:00',
            ExpectedDateTime: '2017-04-29T12:16:19',
            DisplayTime: '4 min',
            JourneyNumber: 20466,
            Deviations: null
          },
          {
            GroupOfLine: null,
            TransportMode: 'BUS',
            LineNumber: '118',
            Destination: 'Hallonbergen',
            JourneyDirection: 2,
            StopAreaName: 'Spånga station',
            StopAreaNumber: 12138,
            StopPointNumber: 50080,
            StopPointDesignation: 'A',
            TimeTabledDateTime: '2017-04-29T12:19:00',
            ExpectedDateTime: '2017-04-29T12:19:00',
            DisplayTime: '6 min',
            JourneyNumber: 41371,
            Deviations: null
          }
        ],
        Trains: [
          {
            SecondaryDestinationName: null,
            GroupOfLine: null,
            TransportMode: 'TRAIN',
            LineNumber: '35',
            Destination: 'Nynäshamn',
            JourneyDirection: 1,
            StopAreaName: 'Spånga',
            StopAreaNumber: 6041,
            StopPointNumber: 6041,
            StopPointDesignation: '4',
            TimeTabledDateTime: '2017-04-29T12:19:00',
            ExpectedDateTime: '2017-04-29T12:19:00',
            DisplayTime: '6 min',
            JourneyNumber: 2831,
            Deviations: null
          },
          {
            SecondaryDestinationName: null,
            GroupOfLine: null,
            TransportMode: 'TRAIN',
            LineNumber: '35',
            Destination: 'Kungsängen',
            JourneyDirection: 2,
            StopAreaName: 'Spånga',
            StopAreaNumber: 6041,
            StopPointNumber: 6042,
            StopPointDesignation: '3',
            TimeTabledDateTime: '2017-04-29T12:26:00',
            ExpectedDateTime: '2017-04-29T12:26:00',
            DisplayTime: '13 min',
            JourneyNumber: 2530,
            Deviations: null
          },
          {
            SecondaryDestinationName: null,
            GroupOfLine: null,
            TransportMode: 'TRAIN',
            LineNumber: '35',
            Destination: 'Västerhaninge',
            JourneyDirection: 1,
            StopAreaName: 'Spånga',
            StopAreaNumber: 6041,
            StopPointNumber: 6041,
            StopPointDesignation: '4',
            TimeTabledDateTime: '2017-04-29T12:34:00',
            ExpectedDateTime: '2017-04-29T12:34:00',
            DisplayTime: '12:34',
            JourneyNumber: 2533,
            Deviations: null
          },
          {
            SecondaryDestinationName: null,
            GroupOfLine: null,
            TransportMode: 'TRAIN',
            LineNumber: '35',
            Destination: 'Bålsta',
            JourneyDirection: 2,
            StopAreaName: 'Spånga',
            StopAreaNumber: 6041,
            StopPointNumber: 6042,
            StopPointDesignation: '3',
            TimeTabledDateTime: '2017-04-29T12:41:00',
            ExpectedDateTime: '2017-04-29T12:41:00',
            DisplayTime: '28 min',
            JourneyNumber: 2830,
            Deviations: null
          }
        ],
        Trams: [],
        Ships: [],
        StopPointDeviations: [
          {
            StopInfo: {
              StopAreaNumber: 6041,
              StopAreaName: 'Spånga',
              TransportMode: 'TRAIN',
              GroupOfLine: ''
            },
            Deviation: {
              Text: 'Sträckan Sundbyberg-Jakobsberg och omvänt ersätts med buss och tunnelbana söndagar till kl 08:50 pga banarbete. Se anslag på stationen samt sl.se.',
              Consequence: null,
              ImportanceLevel: 5
            }
          }
        ],
        StopAreaName: 'Spånga station'
      }
]
}
